//    THE MEMBER FUNCTIONS OF THIS CLASS ALLOW TO MANAGE 
//    THE PERIODICITY OF THE THREADS GENERATED BY THE  
//    PTHREAD.H LIBRARY 

#ifndef THREAD_FUNCTIONS_H_INCLUDED 
#define THREAD_FUNCTIONS_H_INCLUDED 
//#include "/home/pi/comdemo_/include/typeDef.h"
//#include "/home/pi/comdemo_/include/ext_dep.h"

#include "typeDef.h"
#include "ext_dep.h"

struct task_par {
	 int arg; /* task argument */
	 long wcet; /* in microseconds */
	 int period; /* in milliseconds */
	 int deadline; /* relative (ms) */
	 int priority; /* in [0,99] */
	 int dmiss; /* no. of misses */
	 struct timespec at; /* next activ. time */
	 struct timespec dl; /* abs. deadline */
};

struct sched_param;

struct timespec;

class thread_functions{
	
	public:
	     thread_functions();
	     void set_period(task_par *tp);
	     void wait_for_period(task_par *tp);
     private:
         void time_add_ms(timespec *t, int ms);
         void time_copy(timespec *td, timespec ts);
         
};

#endif
